### ISSUE TITLE
Cannot install: An error has occurred

### ISSUE THREAD

**Issue by jspicher** [WojtekTB/Chesscom-to-lichess-games#10]
Great extension idea! I'm getting this error when trying to install from google chrome store: 
[image](https://user-images.githubusercontent.com/932396/120901830-0f62b880-c60b-11eb-8a08-90a3acd735c7.png)

**Comment by WojtekTB** [comment]
Hello, I am aware of the problem and I think I have fixed it, but the approval process for the chrome web store is taking forever so it might take some time for it to take effect.

**Comment by jspicher** [comment]
Cool thanks man, it's installing fine now.
