### ISSUE TITLE
Import  button not working and clicking on extension gives popup to use import button

### ISSUE THREAD

**Issue by prashantkhurana** [WojtekTB/Chesscom-to-lichess-games#11]
1. Clicking on extension used to work but now it gives a popup saying use the import button. 
2. Import button was working until yesterday but now opens the pgn share dialog on chess.com

Using chrome extension, updated to newest version.

**Comment by WojtekTB** [comment]
Hey, I submitted a fix to google web store, but it will take some time to update. Thanks for the report
