### ISSUE TITLE
Chesscom to Lichess games seems to be broken?

### ISSUE THREAD

**Issue by WarpWing** [WojtekTB/Chesscom-to-lichess-games#13]
Hello! I was trying to use the extension on firefox when this occured when I was on a chess.com game trying to import it into a lichess study

![image](https://user-images.githubusercontent.com/28925758/121774595-16c91b00-cb51-11eb-8d48-3c3ea93d48de.png)

Any idea why this occurs? I'm using the custom built one from the repository

**Comment by WojtekTB** [comment]
Hey, chess.com recently updated one of its class names causing the code to not be able to find the right button. Update to the latest version of the repo and it should work

**Comment by WarpWing** [comment]
Thanks :D
