### ISSUE TITLE
Extension Broken?

### ISSUE THREAD

**Issue by brttrssll** [WojtekTB/Chesscom-to-lichess-games#14]
Similar to the issue WarpWing shared 16 days ago, the "import" button only pulls up the share pop-up.

**Comment by WojtekTB** [comment]
Hey, yeah some of the class names on the website changed so the extension can't find the buttons anymore. I will work on a more permanent solution to this problem later but I can't be bothered to fix it every 5 days it changes atm

**Comment by temp-name-remember-to-change-later** [comment]
It seems to be a lot simpler than that; I'm not really familiar with Javascript, but it seems to me that it was trying to click the PGN tab button before it was available to click. I just changed the first timeout (line 132 in injectHtmlButtonToPage.js) from 1ms to 500ms and it worked again. It looks like you just need to wait for the "share" box to load, then it all works fine.
