### ISSUE TITLE
Extension Compatability support

### ISSUE THREAD

**Issue by WarpWing** [WojtekTB/Chesscom-to-lichess-games#2]
Hello! So I heard that this extension is Firefox Compatible. I was wondering how I could install this extension for Firefox?

**Comment by PhilLecl** [comment]
You need a signed .xpi file. You can [make one yourself](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) or use the one I've uploaded [here](https://github.com/PhilLecl/Chesscom-to-lichess-games/files/6571286/firefox.zip). Then, go to `about:addons`, click the gear icon, select "Install from file" and finally select the xpi.

**Comment by WarpWing** [comment]
> You need a signed .xpi file. You can [make one yourself](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/) or use the one I've uploaded [here](https://github.com/PhilLecl/Chesscom-to-lichess-games/files/6571286/firefox.zip). Then, go to `about:addons`, click the gear icon, select "Install from file" and finally select the xpi.

Ah thx, I'm not too good with building stuff from scratch! Thanks ^^
