### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by PhilLecl** [WojtekTB/Chesscom-to-lichess-games#7]
A reverse image search shows that the current logo is used by [Uniswap](https://en.wikipedia.org/wiki/Uniswap). 

I'm not sure about the copyright/trademark implications, but I'd recommend changing the logo to a chess-related one with a Creative Commons license.

**Comment by WojtekTB** [comment]
That is true, I did just pull a random icon I had on my pc. Open to suggestions, will prob post a couple candidates here and we can see which one looks best

**Comment by WojtekTB** [comment]
Thoughts on this one? https://search.creativecommons.org/photos/163d77e7-6601-4b0e-bd65-280573b26974

**Comment by PhilLecl** [comment]
Looks alright to me, but maybe an image with a square aspect ration would be better suited as a logo?

Freesvg as some good ones as well:
https://freesvg.org/chess-piece-rook
https://freesvg.org/chess-piece-silhouette-image
https://freesvg.org/vector-image-of-chess-horse

**Comment by WojtekTB** [comment]
![logo](https://user-images.githubusercontent.com/34536619/120735664-dc4fe600-c49f-11eb-9e39-02783aa2c5f2.png)
gonna use this for now, if anyone with more artistic talent comes along and proposes something better, so be it
