### ISSUE TITLE
Cannot add extension on brave

### ISSUE THREAD

**Issue by kerbless** [WojtekTB/Chesscom-to-lichess-games#9]
![image](https://user-images.githubusercontent.com/32358946/120761036-10192300-c515-11eb-802b-4de0a808ca9f.png)
I get the (image) error. I'm using Brave Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)

**Comment by WojtekTB** [comment]
Hey, so I am in the middle of updating the extension everywhere so gotta wait for approval of the new version where we changed the icon. Gonna check in on this when that happens

**Comment by WojtekTB** [comment]
As it turns out this was not a problem related to brave. closing this issue as it should be fixed in the next update
